name: Deploy Backend

on:
  push:
    branches:
      - prod
    paths:
      - 'backend/core-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect and deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/SnipCrate
            git pull
            cd backend/core-api
            docker rm -f snipcrate-api || true
            docker build -t snipcrate-api:latest -f SnipCrate.Api/Dockerfile .
            docker run -d --name snipcrate-api -p 8080:8080 --restart unless-stopped snipcrate-api:latest

